### ISSUE TITLE
ESP crash when the server disconnect and try to reconnect

### ISSUE THREAD

**Issue by Tibus** [i-n-g-o/esp-mqtt-arduino#1]
Hello,

In your subscribe exemple, when the server disconnect, the esp try to reconnect to it... but if the server is really down, so the esp can't reconnect to it, the esp crash.

**Comment by i-n-g-o** [comment]
hi.
thanks for reporting. i will have a look.

**Comment by i-n-g-o** [comment]
it took a while...  ;)
i tried to reproduce with the mqtt_sub example. connected and killed the server.
the esp did not crash.

the reconnect mechanism in the examples was not good so i updated the examples.

what excactly did you do? could you verify?
thanks
