### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by kiralikbeyin** [i-n-g-o/esp-mqtt-arduino#10]
This lib is better than any other mqtt libs because it works without any problem and very easy to use.

Last commit was 10 months ago will you discontinue @i-n-g-o ?

**Comment by i-n-g-o** [comment]
just updated the lib so it's in the same state as https://github.com/tuanpmt/esp_mqtt
(esp_mqtt commit: 7ec2ef8e1df0422b77348fe1da7885568e0c9d01)
pushed to version 1.0.1

**Comment by kiralikbeyin** [comment]
Hi,

There is a new commit : Latest commit 37cab7c  on Jul 24 https://github.com/tuanpmt/esp_mqtt

Please can you update?
Thanks.

**Comment by i-n-g-o** [comment]
added relevant changes from https://github.com/tuanpmt/esp_mqtt

commits:
80abcbf3a9b8e9b35f8345a8656b3076b3d9bc47
c7eda3308454b353ca19646de8dfdcba41d4904e

**Comment by i-n-g-o** [comment]
please reopen this issue, if there are relevant changes in
https://github.com/tuanpmt/esp_mqtt
