### ISSUE TITLE
Conditinal include

### ISSUE THREAD

**Issue by kiralikbeyin** [i-n-g-o/esp-mqtt-arduino#15]
I have a variable in eeprom.

How can i do
if variable is true #include MQTT.h or change buffer sizes in mqtt_config.h ?

**Comment by i-n-g-o** [comment]
"#include" and "#define" are preprocessor directives and therefore cannot be changed at runtime.

buffersize is defined in mqtt_config.h:
`#define MQTT_BUF_SIZE		1024`

to change the buffersize it would need to be a variable and there has to be a way to set it. best to set this only once.

**Comment by i-n-g-o** [comment]
why would you want to change the buffersize during runtime?

**Comment by kiralikbeyin** [comment]
My current setup 
```

#define MQTT_BUF_SIZE		2048 //1024
#define QUEUE_BUFFER_SIZE		 	2048	//2048
```
Because i am sending 1500bytes json data.

1-I have a conditional setup for user; AP mode or Station mode. If ESP is in AP mode so there is no internet connection and i can't use MQTT (i am switching to web socket connection)
2-I don't know if mqtt streaming is possible so i can use smaller size.

I have a lot of other things in sketch and my free heap is generally 5000. That is why i need more free heap.

**Comment by i-n-g-o** [comment]
the only chance you have is to create a mqtt client or not (or destroy it), depending on your setting...

afaik the buffersize defines the size of some internal buffers, your data does not need to fit in that buffer as a whole: i think it does support multi-part messages.
i never tried it though...

**Comment by kiralikbeyin** [comment]
I tried to destroy but couldn't make. Is there any trick?

#define MQTT_BUF_SIZE		2048 //1024 
If i reduce buffer size to original value 1024, i can't send 1500bytes. .

I will try with latest lib today

**Comment by kiralikbeyin** [comment]
Latest commit works with multi-part as you said.
My current setting
```
#ifndef __MQTT_CONFIG_H__
#define __MQTT_CONFIG_H__

//#define MQTT_SSL_ENABLE

/*DEFAULT CONFIGURATIONS*/

#define MQTT_BUF_SIZE		256 //1024
#define MQTT_KEEPALIVE		120	 /*second*/

#define MQTT_RECONNECT_TIMEOUT 	5	/*second*/

#define QUEUE_BUFFER_SIZE		 512//		2048

#define PROTOCOL_NAMEv31	/*MQTT version 3.1 compatible with Mosquitto v0.15*/
//PROTOCOL_NAMEv311			/*MQTT version 3.11 compatible with https://eclipse.org/paho/clients/testing/*/

#endif // __MQTT_CONFIG_H__
```

I have 11500 heap now (+6500) 

Thanks!

**Comment by i-n-g-o** [comment]
> I tried to destroy but couldn't make. Is there any trick?

what do you mean?

**Comment by kiralikbeyin** [comment]
MQTT.cpp line 129
I tried to use this but esp crashes..

```
MQTT::~MQTT()
{
	MQTT_DeleteClient(&mqttClient);
}
```


I added 

```
//MQTT.cpp
void MQTT::destroy()
{
	MQTT_DeleteClient(&mqttClient);
}

//MQTT.h
void destroy();

```

but didn't work..

**Comment by kiralikbeyin** [comment]
If you don't need MQTT while in the loop thats how to delete and free (5000-7000) heap
MQTT.cpp
```
void MQTT::sil(const char* client_id)
{
	MQTT_sil(&mqttClient, client_id);
}
```

MQTT.h
```
void sil(const char* client_id);
```

mqtt.h
```
void ICACHE_FLASH_ATTR MQTT_sil(MQTT_Client *mqttClient, const char* client_id);
```

mqtt.c
```
void ICACHE_FLASH_ATTR
mqtt_client_delete(MQTT_Client *mqttClient)
{
..
...

/* COMMENT THIS BLOCK - OR SOMEHOW IT WILL CRUSH
  if (mqttClient->user_data != NULL) {
    os_free(mqttClient->user_data);
    mqttClient->user_data = NULL;
  }
*/
...
...
}

//ADD
void ICACHE_FLASH_ATTR
MQTT_sil(MQTT_Client *mqttClient, const char* client_id)

{
  if (NULL == mqttClient)
    return;

  mqttClient->connState = MQTT_DELETED;
  // if(TCP_DISCONNECTED == mqttClient->connState) {
  //  mqttClient->connState = MQTT_DELETED;
  // } else if(MQTT_DELETED != mqttClient->connState) {
  //  mqttClient->connState = MQTT_DELETING;
  // }

  system_os_post(MQTT_TASK_PRIO, 0, (os_param_t)mqttClient);
  os_timer_disarm(&mqttClient->mqttTimer);
}
```


in your skectch
myMqtt.sil(mc.c_str());
