### ISSUE TITLE
QOS

### ISSUE THREAD

**Issue by SensorsIot** [i-n-g-o/esp-mqtt-arduino#3]
I use your library to do some tests. So far, it works good in both directions.
Now I tried QOS 1 for a subscription (topic: command). To test, I send a command: OFF from the broker (cloudMQTT) and reset the ESP. During boot I send a Command:ON from the broker. Theory (as I understand) says, that the library should now get the ON command right after startup. But it does not get it.

**Comment by i-n-g-o** [comment]
i never tested QOS.
the mqtt part of the library originates from here: https://github.com/tuanpmt/esp_mqtt
just realized, that there are some updates... maybe those help.

**Comment by i-n-g-o** [comment]
just updated to current master of https://github.com/tuanpmt/esp_mqtt.
i did not test QOS, but it might have changed.
would you mind testing it?
