### ISSUE TITLE
Secure connection

### ISSUE THREAD

**Issue by SensorsIot** [i-n-g-o/esp-mqtt-arduino#4]
The library works for unsecured connections. I was happy when I saw, that it is able to use secure connections, too. I am not experienced with secure connections. Is there a description/tutorial available?

**Comment by i-n-g-o** [comment]
hi.
i just had a look and something changed, so the secure branch does not compile anymore.

the idea is, that you pass an additional argument to the constructor of the MQTT object to control the secureness:
`MQTT(const char* client_id, const char* host, uint32_t port, uint8_t security = 0);`

this would use ssl:
`MQTT myMqtt(CLIENT_ID, "192.168.1.50", 1883, 1);`

**Comment by i-n-g-o** [comment]
i updated to current master of https://github.com/tuanpmt/esp_mqtt
secure branch should compile again. tested it with arduino-esp8266 2.1.0-rc2
