### ISSUE TITLE
"Last Will and Testament"

### ISSUE THREAD

**Issue by empty1993** [i-n-g-o/esp-mqtt-arduino#5]
Hi guy !
At first, thank for your library, it's very nice. I have a question, how can i use LWT ? I opened your code and saw this "MQTT_InitLWT(&mqttClient, "/lwt", "offline", 0, 0);", but when i disconnected my esp, i couldnt get any message in /lwt topic. Can you help me ? .
Sr for my bad English.

**Comment by i-n-g-o** [comment]
hi.
i never used the last-will-topic myself, so i can't really comment about it. and i don't have an esp on my hand right now, so i cannot test until next week.

i will update the underlying library from https://github.com/tuanpmt/esp_mqtt soon. it might change or fix something.

**Comment by candale** [comment]
Hi,

I believe the last will is sent after `keepalive_interval` seconds. `keepalive_interval` represents
`[...] the number of seconds after which the bridge should send a ping if no other traffic has occurred. Defaults to 60. A minimum value of 5 seconds is allowed.` (from the [mosquitto conf documentation](http://mosquitto.org/man/mosquitto-conf-5.html). So it will figure out that the device is disconnected after `keepalive_interval` seconds. Try and wait for 60 seconds before checking if the lwt is sent or change the setting in your MQTT broker.

Another thing to know is that the last will is sent only if a forced disconnect has happened. If your client has issued a polite disconnect, the last will will not be sent. `The Last Will and Testament (LWT) feature is used in MQTT to notify other clients about an ungracefully disconnected client.` from [this](http://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament) article.

Hope it helps.

**Comment by empty1993** [comment]
Thank for your help !
@candale , as you said, i waited for 60 seconds and my broker ( mosquitto ) told me that my esp8266 disconnected, but i got nothing from my android ( i use this app from [https://play.google.com/store/apps/details?id=at.tripwire.mqtt.client](url). But, when i used this library [https://github.com/tuanpmt/espduino](url) (i think espduino library is same esp_mqtt library) to connect arduino + esp8266 + MQTT....it works very well, and i can receive the message from /lwt topic. I very very like the library of @i-n-g-o, i'm just a newbie and it's easy to use for me, i hope he will update this library soon :).

**Comment by i-n-g-o** [comment]
just updated to current master of https://github.com/tuanpmt/esp_mqtt.
i did not test LWT, but it might have changed.
would you mind testing it?

**Comment by empty1993** [comment]
It worked very well...thank you a lot.

**Comment by ftheirs** [comment]
hi @empty1993 could you put some dummy code to use LWT? I'm a newbie in ESP8266 world and I need some help.
Thanks!!
