### ISSUE TITLE
using Async connection for a Server - Clinets connection

### ISSUE THREAD

**Issue by mkeyno** [i-n-g-o/esp-mqtt-arduino#7]
hi @i-n-g-o  sorry to make the issue for my question , actually I've planned to set a ESP module as AP and other ESP module as Station mode and like IOT home , the server received and send command to those , Iggre told me I should use   asyinc lib instead of Esp8266WebServer lib , I really appreciated if you could guide me to what strategy should follow

**Comment by i-n-g-o** [comment]
Hi. sorry for the late reply.
you could roll your own. have a look here: https://github.com/i-n-g-o/esp-socket
for just sending some bytes around in your own protocol (without http), you would just need tcp-sockets (server, client)
if you need http, you could have a look into Esp8266WebServer to see how http support is done there.
