### ISSUE TITLE
rc 2.3 wifi connection problem

### ISSUE THREAD

**Issue by kiralikbeyin** [i-n-g-o/esp-mqtt-arduino#8]
I asked and answered myself :)

myMqtt.setUserPwd(CLIENT_ID, mqtt_password); 

+++
Waaaww it really publish very fast without error :) no delay in loop 👍You are crazy!

void loop() { 
  String got = String(random(987654321, 9876543210));
  String topic("users/34efdc34fre");
  myMqtt.publish(topic, got + got + got );
}
+++

**Current examples can't connect to wifi because of some problem with rc2.3 i think...**

Maybe you can try to make something new with https://github.com/tzapu/WiFiManager it has some mqtt parameter when connecting to wifi

**Comment by kiralikbeyin** [comment]
ok found;

`  myMqtt.setUserPwd(CLIENT_ID, mqtt_password);
`

i tried to subscribe /xxx/xxxxx/# 

I think # is not working?

**Comment by i-n-g-o** [comment]
hi.
great you made it work :)
i just tried one of the examples with 2.3-rc2. it did connect to my wifi without any problems...
do you have any insights about the problems were facing?

**Comment by i-n-g-o** [comment]
WiFiManager looks cool. with it you can store additional parameters to a wifi setting. that's nice, so you can pull out your e.g. mqtt server address from the config when you are connecting to a certain AP.

**Comment by kiralikbeyin** [comment]
I tried again and no problem now maybe a poor wifi connection 

This lib goes well with mosca lib but i can't upload node server to heroku.. Now i am focused with mosca.

Do you have any suggestions for cloud server?

**Comment by kiralikbeyin** [comment]
Publishing from esp is good but we need a server also, i hope this helps someone...

Forget heroku i deployed mosca and mongo with digital ocean very easly 10$ free credit here --> https://m.do.co/c/38b1c11ea6ea they send an email if you add a payment method, write DROPLET10 to promo code. Totally 20 $ means 4 months :)

First install once click deploy node.js

2-Follow this https://www.digitalocean.com/community/tutorials/how-to-set-up-automatic-deployment-with-git-with-a-vps

3-Install mongo https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

No headache happy developer :)
